Task set 1(1)

In [ ]:
import numpy as np
empty_arr = np.empty((2,2))
print("An empty array of size 2x2 is: ", empty_arr)

An empty array of size 2x2 is:  [[4.97321661e-310 0.00000000e+000]
 [6.24876427e-024 6.60497497e-310]]


Task set 1(2)

In [ ]:
import numpy as np
one_array = np.ones((4,2))
print("An array of ones of size 4x2 is: ", one_array)

An array of ones of size 4x2 is:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task set 1(3)

In [ ]:
import numpy as np
fill_value = np.full((4,2), 10.1, dtype=int)
print("An array of given shape and type filled with fill_value is: ", fill_value)

An array of given shape and type filled with fill_value is:  [[10 10]
 [10 10]
 [10 10]
 [10 10]]


Task set 1(4)

In [ ]:
import numpy as np
array = np.arange(0,9).reshape(3,3)
print(array)
zero_array = np.zeros_like(array, int)
print(zero_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Task set 1(5)

In [ ]:
import numpy as np
array = np.arange(0,9).reshape(3,3)
print(array)
one_array = np.ones_like(array, int)
print(one_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Task set 1(5)

In [ ]:
import numpy as np
new_list = [1,2,3,4]
print(new_list)
arr = np.array(new_list)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


Task set 2

In [ ]:
import numpy as np
range_arr = np.arange(10)
print("An array given range is \n", range_arr, "with dimensions", range_arr.shape,"\n")
# return evenly spaced values within a given interval.
linspace_arr = np.linspace(2.0, 3.0, num = 5, endpoint = False)
# if endpoint = True, stop=3.0 here is included otherwise its not included
print("An evenly spaced array of given range is \n", linspace_arr, "with dimensions", linspace_arr.shape, "\n")
# return evenly spaced numbers over a specified interval.

An array given range is 
 [0 1 2 3 4 5 6 7 8 9] with dimensions (10,) 

An evenly spaced array of given range is 
 [2.  2.2 2.4 2.6 2.8] with dimensions (5,) 



Task set 2(1)

In [ ]:
import numpy as np
range_arr = np.arange(10,50)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task set 2(2)

In [ ]:
import numpy as np
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task set 2(3)

In [ ]:
import numpy as np
identity_matrix = np.eye(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


Task set 2(4)

In [ ]:
import numpy as np
random = np.random.random(30)
print(random)
mean = np.mean(random)
print(mean)

[0.00106065 0.52526816 0.40661104 0.72147282 0.8489262  0.25176471
 0.34973412 0.84046203 0.96065377 0.72175139 0.63786185 0.57146766
 0.17073106 0.78691469 0.95814218 0.08916608 0.30865453 0.37665412
 0.28939143 0.4626514  0.9555436  0.950359   0.74171352 0.86416117
 0.38371869 0.08088565 0.4143492  0.1661     0.56177537 0.52223259]
0.530672622336403


Task set 2(5)

In [ ]:
import numpy as np
array = np.random.random(100).reshape(10,10)
print(array)
print(np.max(array))
print(np.min(array))

[[0.95189284 0.77430763 0.08928617 0.48071827 0.68087337 0.7742632
  0.44620149 0.64902394 0.72963879 0.79144551]
 [0.73948191 0.76729333 0.53790758 0.40347205 0.23146694 0.11722449
  0.55643919 0.00232062 0.30575372 0.63915299]
 [0.2228674  0.39583606 0.70548891 0.69146507 0.49144356 0.56033554
  0.53783495 0.75318477 0.93995952 0.72663374]
 [0.91872869 0.01315982 0.25268967 0.96273023 0.4623543  0.41095631
  0.98511027 0.43401168 0.16406136 0.2251578 ]
 [0.64183276 0.14604579 0.13023158 0.2387089  0.44896698 0.73922592
  0.00141461 0.46427734 0.98938554 0.80083018]
 [0.50508376 0.46549258 0.58827454 0.36395753 0.5710554  0.8083595
  0.44357722 0.40423051 0.66761499 0.20301042]
 [0.46441003 0.10489309 0.17962119 0.11943623 0.40092449 0.32710065
  0.98116434 0.80658267 0.50924855 0.96954328]
 [0.06031229 0.2922952  0.90315708 0.54537951 0.82784859 0.50732181
  0.33348557 0.85152733 0.23180995 0.45632298]
 [0.58271916 0.09506952 0.9728217  0.19313969 0.29959042 0.8276207
  0.97672706 0.

Task set 2(6)

In [ ]:
import numpy as np
array = np.random.random(10)
print(array)
zero_array = np.zeros_like(array, int)
print(zero_array)
index = [4]
new_value = [1]
zero_array[index] = new_value
print(zero_array)

[0.24735883 0.77106754 0.85662636 0.03638494 0.03145727 0.17693332
 0.77017251 0.19217682 0.70561365 0.53357129]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


Task set 2(7)

In [ ]:
import numpy as np
array = [1,2,0,0,4,0]
print(np.array(array))
print(np.flip(array))

[1 2 0 0 4 0]
[0 4 0 0 2 1]


Task set 2(8)

In [ ]:
import numpy as np
array = np.ones((5,5))
print(array)
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task set 2(9)

In [ ]:
import numpy as np
array = np.ones((8,8))
array[::2, 1::2] = 0
array[1::2, ::2] = 0
print(array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Task set 3.3.1(1)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
print(np.add(x,y))

v = np.array([9,10])
w = np.array([11,12])
print(v)
print(w)
print(np.add(v,w))


[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 13]]
[ 9 10]
[11 12]
[20 22]


Task set 3.3.1(2)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
print(np.subtract(x,y))

v = np.array([9,10])
w = np.array([11,12])
print(v)
print(w)
print(np.subtract(v,w))

[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -3]]
[ 9 10]
[11 12]
[-2 -2]


Task set 3.3.1(3)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(x)
print(np.array(x) * 2)
print(y)
print(np.array(y) * 2)

v = np.array([9,10])
w = np.array([11,12])
print(v)
print(np.array(v) * 2)
print(w)
print(np.array(w) * 2)

[[1 2]
 [3 5]]
[[ 2  4]
 [ 6 10]]
[[5 6]
 [7 8]]
[[10 12]
 [14 16]]
[ 9 10]
[18 20]
[11 12]
[22 24]


Task set 3.3.1(4)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x)
print(np.square(x))
print(y)
print(np.square(y))
print(v)
print(np.square(v))
print(w)
print(np.square(w))

[[1 2]
 [3 5]]
[[ 1  4]
 [ 9 25]]
[[5 6]
 [7 8]]
[[25 36]
 [49 64]]
[ 9 10]
[ 81 100]
[11 12]
[121 144]


Task set 3.3.1(5)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

219
[29 77]
[[19 22]
 [50 58]]


Task set 3.3.1(6)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x)
print(y)
print(np.concatenate((x,y), axis=0))
print(np.concatenate((x,y), axis=1))

v = v.reshape(-1,1)
w = w.reshape(-1,1)
print(v)
print(w)
print(np.concatenate((v,w), axis=0))
print(np.concatenate((v,w), axis=1))

[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]
[[ 9]
 [10]]
[[11]
 [12]]
[[ 9]
 [10]
 [11]
 [12]]
[[ 9 11]
 [10 12]]


Task set 3.3.1(7)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
print(np.concatenate(x,v), axis=0)

TypeError: only integer scalar arrays can be converted to a scalar index

We get the error because in order for two arrays to be concatenated, the rows of the arrays need to be same.

Task set 3.3.2A(1)

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
AT = np.transpose(A)
I = np.identity(2)
print(I)
print(AT)
AAT = np.dot(A,AT)
print(AAT)
if np.array_equal(AAT, I):
  print("Proved.")
else:
  print("Could not be proved.")

[[1. 0.]
 [0. 1.]]
[[3 7]
 [4 8]]
[[ 25  53]
 [ 53 113]]
Could not be proved.


Task set 3.3.2A(2)

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)
if np.array_equal(AB, BA):
  print("Could not be proved.")
else:
  print("Proved.")


[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Proved.


Task set 3.3.2A(3)

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A, B)
ABT = np.transpose(AB)
print(ABT)
BT = np.transpose(B)
AT = np.transpose(A)
BTAT = np.dot(BT, AT)
print(BTAT)

if np.array_equal(ABT, BTAT):
  print("Proved.")
else:
  print("Could not be proved.")

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
Proved.


Task set 3.3.2B

In [ ]:
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
Ainverse = np.linalg.inv(A)
X = np.dot(Ainverse, B)
print(X)

[ 2.  1. -2.]


Pandas

In [ ]:
import pandas as pd
print(pd.DataFrame({'Bob':['I liked it.','It was awful.'], 'Sue':['Pretty good.','Bland.']}))
print(pd.DataFrame({'Bob':['I liked it.','It was awful.'], 'Sue':['Pretty good.','Bland.']}, index = ['Product A', 'Product B']))

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.
                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.


Exercise 1

In [ ]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(io.BytesIO(uploaded[file_name]))
df.info()

# identify columns with dtype=object
object_columns = df.select_dtypes(include=['object']).columns
print("\nColumns with dtype=object")
print(object_columns)

# display unique values and null counts for each object column
for col in object_columns:
  unique_values = df[col].unique()
  null_count = df[col].isnull().sum()

  print(f"\nColumn: {col}")
  print(f"Unique Values: {unique_values}")
  print(f"Total Null Values: {null_count}")

# dropping columns with dtype=object
numeric_df = df.drop(columns=object_columns)

# saving in new csv file
numeric_file_path = "banknumericdata.csv"
numeric_df.to_csv(numeric_file_path)

# read banknumericdata.csv
numeric_data = pd.read_csv(numeric_file_path)
summary_stats = numeric_data.describe()
print("Summary statistics: ")
print(summary_stats)



Saving bank.csv to bank (7).csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

Columns with dtype=object
Index(['job', 'marital', 'education', 'd

Exercise 2

In [ ]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(io.BytesIO(uploaded[file_name]))
df.info()

# identifying columns with null values
columns_with_null_values = df.columns[df.isnull().any()]
print("Columns with null values: ")
print(columns_with_null_values)

# filling missing values
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Height'].fillna(df['Height'].mean(), inplace=True)
df['Weight'].fillna(df['Weight'].mean(), inplace=True)
df['BMI'].fillna(df['BMI'].mean(), inplace=True)
df['Gender'].fillna(method='ffill', inplace=True)
df['Blood type'].fillna(method='ffill', inplace=True)
df['Temperature'].fillna(df['Temperature'].mean(), inplace=True)
df['Heart Rate'].fillna(df['Heart Rate'].mean(), inplace=True)
df['Blood Pressure'].fillna(df['Blood Pressure'].mean(), inplace=True)
df['Cholesterol'].fillna(df['Cholesterol'].mean(), inplace=True)
df['Diabetes'].fillna(method='ffill', inplace=True)
df['Smoking'].fillna(method='ffill', inplace=True)

print("\nMissing values: ")
print(df.isnull().sum())

num_duplicates = df.duplicated().sum()
if num_duplicates > 0:
  df.drop_duplicates(inplace = True)
  print(f"\nDropped {num_duplicates} duplicate rows.")

num_remaining_duplicates = df.duplicated().sum()
print(f"\nRemaining duplicates after cleaning: {num_remaining_duplicates}")

Saving medical_students_dataset.csv to medical_students_dataset (7).csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object 
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood type      180000 non-null  object 
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object 
 12  Smoking         180000 non-null  object 
dtypes: float64(9), object(4)
memory usage: 19.8+ MB
Columns with null values: 
Index(['Student ID', 'Age', 'Gender', 'Height',

1. Student id: I did not impute this data as the missing values of student id might indicate data entry issue or specific reason for not having an ID.

2. Age, Height, Weight, and BMI: Mean imputation as this preserves the overall tendency of the age distribution.

3. Gender: ffill method as the mising values are sparse and gender is consistent across observation.

4. Blood type: ffill imputation as B is the most dominant blood type in the dataset.

5. Temperature, Heart rate, Blood pressure and cholestrol: Mean imputation as these maintain the statistical characteristics of each variable.

6. Diabetes, Smoking: Filling with most frequest answer i.e. no in this case.

Exercise 3

In [ ]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

# binary transformation
df['schoolsup_binary']=df['schoolsup'].apply(lambda x: 1 if x == 'yes' else 0)
df['internet_binary']=df['internet'].apply(lambda x: 1 if x == 'yes' else 0)
df['activities_binary']=df['activities'].apply(lambda x: 1 if x == 'yes' else 0)
df.head()

# ordinal no. transformation
ordinal_cols = ['Medu', 'reason', 'guardian', 'studytime', 'health']
for col in ordinal_cols:
  df[f'{col}_ordinal'] = df[col].astype('category').cat.codes
df.head()

# convert age to interval datatype and create a new column named category_age
def categorize_age(age):
  if 15 <= age <= 17:
    return 'interval1'
  elif 18 <= age <= 20:
    return 'interval2'
  elif age >= 21:
    return 'interval3'
  else:
    return 'interval4'

df['category_age'] = df['age'].apply(categorize_age)
df.head()

# create a new column named passed based on the values in the G3 column
df['passed'] = df['G3'].apply(lambda x: 'yes' if x >= 8 else 'no')
df.head()


Saving performance.csv to performance (5).csv


school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  schoolsup_binary internet_binary  activities_binary  Medu_ordinal  \
0                1               0                  0             4   
1                0               1                  0             1   
2                1               1                  0             1   
3                0               1                  1             4   
4                0               0                  0             3   

   reason_ordinal guardian_ordinal studytime_ordinal health_ordinal  \
0               0                1                 1              2   
1               0                0                 1              2   
2               2                1                 1              2   
3               1                1                 2              4   
4               1                0                 1              4   

  category_age passed  
0    interval2     no  
1    interval1     no  
2    interval1    yes  
3    interval1    yes  
4    interval1    yes  

[5 rows x 43 columns]